# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions_service.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19suggestions_service.proto\x12\x05hello\"!\n\x11SuggestionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x12SuggestionResponse\x12\x10\n\x08\x64\x65\x63ision\x18\x01 \x01(\x08\x32T\n\x12SuggestionsService\x12>\n\x07Suggest\x12\x18.hello.SuggestionRequest\x1a\x19.hello.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTIONREQUEST']._serialized_start=36
  _globals['_SUGGESTIONREQUEST']._serialized_end=69
  _globals['_SUGGESTIONRESPONSE']._serialized_start=71
  _globals['_SUGGESTIONRESPONSE']._serialized_end=109
  _globals['_SUGGESTIONSSERVICE']._serialized_start=111
  _globals['_SUGGESTIONSSERVICE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
