# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import suggestions_service_pb2 as suggestions__service__pb2


class SuggestionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Suggest = channel.unary_unary(
                '/hello.SuggestionsService/Suggest',
                request_serializer=suggestions__service__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=suggestions__service__pb2.SuggestionResponse.FromString,
                )
        self.VectorClockUpdate = channel.unary_unary(
                '/hello.SuggestionsService/VectorClockUpdate',
                request_serializer=suggestions__service__pb2.VectorClockInp_sugg.SerializeToString,
                response_deserializer=suggestions__service__pb2.Empty_sugg.FromString,
                )
        self.Kill = channel.unary_unary(
                '/hello.SuggestionsService/Kill',
                request_serializer=suggestions__service__pb2.KillOrder_sugg.SerializeToString,
                response_deserializer=suggestions__service__pb2.Empty_sugg.FromString,
                )


class SuggestionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Suggest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorClockUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Suggest': grpc.unary_unary_rpc_method_handler(
                    servicer.Suggest,
                    request_deserializer=suggestions__service__pb2.SuggestionRequest.FromString,
                    response_serializer=suggestions__service__pb2.SuggestionResponse.SerializeToString,
            ),
            'VectorClockUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorClockUpdate,
                    request_deserializer=suggestions__service__pb2.VectorClockInp_sugg.FromString,
                    response_serializer=suggestions__service__pb2.Empty_sugg.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=suggestions__service__pb2.KillOrder_sugg.FromString,
                    response_serializer=suggestions__service__pb2.Empty_sugg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.SuggestionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuggestionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Suggest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.SuggestionsService/Suggest',
            suggestions__service__pb2.SuggestionRequest.SerializeToString,
            suggestions__service__pb2.SuggestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VectorClockUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.SuggestionsService/VectorClockUpdate',
            suggestions__service__pb2.VectorClockInp_sugg.SerializeToString,
            suggestions__service__pb2.Empty_sugg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.SuggestionsService/Kill',
            suggestions__service__pb2.KillOrder_sugg.SerializeToString,
            suggestions__service__pb2.Empty_sugg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
