# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_system.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14payment_system.proto\x12\x05hello\"I\n\x0ePaymentRequest\x12\x12\n\npayment_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\x12\x13\n\x0b\x63redit_card\x18\x03 \x01(\x03\"\"\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"B\n\x13PaymentConfirmation\x12\x12\n\npayment_id\x18\x01 \x01(\x03\x12\x17\n\x0fperform_payment\x18\x02 \x01(\x08\x32\x9b\x01\n\x14PaymentSystemService\x12=\n\x0cStartPayment\x12\x15.hello.PaymentRequest\x1a\x16.hello.PaymentResponse\x12\x44\n\x0e\x43onfirmPayment\x12\x1a.hello.PaymentConfirmation\x1a\x16.hello.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYMENTREQUEST']._serialized_start=31
  _globals['_PAYMENTREQUEST']._serialized_end=104
  _globals['_PAYMENTRESPONSE']._serialized_start=106
  _globals['_PAYMENTRESPONSE']._serialized_end=140
  _globals['_PAYMENTCONFIRMATION']._serialized_start=142
  _globals['_PAYMENTCONFIRMATION']._serialized_end=208
  _globals['_PAYMENTSYSTEMSERVICE']._serialized_start=211
  _globals['_PAYMENTSYSTEMSERVICE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
