# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x05hello\"2\n\x12OverwriteDBRequest\x12\x1c\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x0c.hello.Field\"*\n\x05\x46ield\x12\x11\n\tbook_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"\x15\n\x13OverwriteDBResponse\"\x1c\n\x0bReadRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05value\x18\x01 \x01(\x05\";\n\x0cWriteRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\r\n\x05\x66resh\x18\x03 \x01(\x08\"\x0f\n\rWriteResponse\"O\n\rModifyRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\r\n\x05\x66resh\x18\x03 \x01(\x08\x12\x11\n\tmodify_id\x18\x04 \x01(\x03\"!\n\x0eModifyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"J\n\x13ModifyCommitRequest\x12\x11\n\tmodify_id\x18\x01 \x01(\x03\x12\x11\n\tto_commit\x18\x02 \x01(\x08\x12\r\n\x05\x66resh\x18\x03 \x01(\x08\"\x16\n\x14ModifyCommitResponse\"-\n\x0bLockRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x0f\n\x07lock_id\x18\x02 \x01(\x03\",\n\x0cLockResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x08other_id\x18\x02 \x01(\x03\"0\n\x0eReleaseRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x0f\n\x07lock_id\x18\x02 \x01(\x03\"\x11\n\x0fReleaseResponse2\xa0\x03\n\x08\x44\x61tabase\x12/\n\x04Read\x12\x12.hello.ReadRequest\x1a\x13.hello.ReadResponse\x12\x32\n\x05Write\x12\x13.hello.WriteRequest\x1a\x14.hello.WriteResponse\x12\x35\n\x06Modify\x12\x14.hello.ModifyRequest\x1a\x15.hello.ModifyResponse\x12G\n\x0cModifyCommit\x12\x1a.hello.ModifyCommitRequest\x1a\x1b.hello.ModifyCommitResponse\x12/\n\x04Lock\x12\x12.hello.LockRequest\x1a\x13.hello.LockResponse\x12\x38\n\x07Release\x12\x15.hello.ReleaseRequest\x1a\x16.hello.ReleaseResponse\x12\x44\n\x0bOverwriteDB\x12\x19.hello.OverwriteDBRequest\x1a\x1a.hello.OverwriteDBResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OVERWRITEDBREQUEST']._serialized_start=25
  _globals['_OVERWRITEDBREQUEST']._serialized_end=75
  _globals['_FIELD']._serialized_start=77
  _globals['_FIELD']._serialized_end=119
  _globals['_OVERWRITEDBRESPONSE']._serialized_start=121
  _globals['_OVERWRITEDBRESPONSE']._serialized_end=142
  _globals['_READREQUEST']._serialized_start=144
  _globals['_READREQUEST']._serialized_end=172
  _globals['_READRESPONSE']._serialized_start=174
  _globals['_READRESPONSE']._serialized_end=203
  _globals['_WRITEREQUEST']._serialized_start=205
  _globals['_WRITEREQUEST']._serialized_end=264
  _globals['_WRITERESPONSE']._serialized_start=266
  _globals['_WRITERESPONSE']._serialized_end=281
  _globals['_MODIFYREQUEST']._serialized_start=283
  _globals['_MODIFYREQUEST']._serialized_end=362
  _globals['_MODIFYRESPONSE']._serialized_start=364
  _globals['_MODIFYRESPONSE']._serialized_end=397
  _globals['_MODIFYCOMMITREQUEST']._serialized_start=399
  _globals['_MODIFYCOMMITREQUEST']._serialized_end=473
  _globals['_MODIFYCOMMITRESPONSE']._serialized_start=475
  _globals['_MODIFYCOMMITRESPONSE']._serialized_end=497
  _globals['_LOCKREQUEST']._serialized_start=499
  _globals['_LOCKREQUEST']._serialized_end=544
  _globals['_LOCKRESPONSE']._serialized_start=546
  _globals['_LOCKRESPONSE']._serialized_end=590
  _globals['_RELEASEREQUEST']._serialized_start=592
  _globals['_RELEASEREQUEST']._serialized_end=640
  _globals['_RELEASERESPONSE']._serialized_start=642
  _globals['_RELEASERESPONSE']._serialized_end=659
  _globals['_DATABASE']._serialized_start=662
  _globals['_DATABASE']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
