# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x05hello\"\x0e\n\x0cTokenRequest\"\x0f\n\rTokenResponse2C\n\rOrderExecutor\x12\x32\n\x05Token\x12\x13.hello.TokenRequest\x1a\x14.hello.TokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOKENREQUEST']._serialized_start=31
  _globals['_TOKENREQUEST']._serialized_end=45
  _globals['_TOKENRESPONSE']._serialized_start=47
  _globals['_TOKENRESPONSE']._serialized_end=62
  _globals['_ORDEREXECUTOR']._serialized_start=64
  _globals['_ORDEREXECUTOR']._serialized_end=131
# @@protoc_insertion_point(module_scope)
