{
 "title": "My dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time since last request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "orchestrator_time_since_last_request{job=\"orchestrator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout trace",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "8bfddf6b", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "checkout-span" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Network latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "network_latency{job=\"orchestrator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verification trace",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "filters": [
      { "id": "8f647c93", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "verification" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Time taken to generate suggestions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "suggestion_duration_milliseconds_bucket{job=\"suggestion_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orchestrator request durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "orchestrator_request_duration_milliseconds_bucket{job=\"orchestrator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of frauds detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "fraud_counter_total{job=\"fraud_detection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total amount of suggestions made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "suggestion_counter_total{job=\"suggestion_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of orders in queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "queue_counter{job=\"order_queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "active_requests_counter{job=\"orchestrator\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}